### ISSUE TITLE
all broke after update

### ISSUE THREAD

**Issue by Dimasmagadan** [unknownuser88/consolewrap#17]
Hello,

your package has just updated and stopped working after that.
nothing else was changed.

I select any variable, press ctrl+shift+q and that's what I see in console:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "consolewrap in xxx/Library/Application Support/Sublime Text 3/Installed Packages/Console Wrap for js.sublime-package", line 130, in run
  File "consolewrap in xxx/Library/Application Support/Sublime Text 3/Installed Packages/Console Wrap for js.sublime-package", line 74, in is_log_string
TypeError: 'NoneType' object is not subscriptable

**Comment by unknownuser88** [comment]
Could you please remove package and settings from (file: consolewrap.sublime-settings) and install it again  and check if you have the same error?

**Comment by Dimasmagadan** [comment]
Uninstalling and installing again helped. Thank you
