### ISSUE TITLE
Error parsing settings

### ISSUE THREAD

**Issue by sm1215** [unknownuser88/consolewrap#22]
Hello, just getting a small error. Removing the trailing comma in my settings file fixed it, but otherwise I couldn't run the plugin. 

```
error: Error trying to parse settings: Trailing comma before closing bracket in C:\Users\...\Console Wrap\.sublime\consolewrap.sublime-settings:8:5
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File ".\console_wrap.py", line 111, in run
  File ".\console_wrap.py", line 83, in runCommand
ValueError: zero length field name in format
```

**Comment by unknownuser88** [comment]
please send me your settings and pick that comma

**Comment by sm1215** [comment]
Looks like you got it,

My settings file just looks like this:

```
{
    "js": {
        "consoleStr"   : "{title}, {variable}", // "{title}, tmpVal = {variable}" to assigne value to temporary parameter output: console.log('title', tmpVal = variable);
        "consoleFunc"  : ["console", "log"],    // You can change default log statement for example ["logger", "info"] output: logger.info('title', variable);
        "single_quotes": false,                 // If true output: console.log('title', variable);
        "semicolon"    : true,                  // If false, will not add semicolon at end of line
        "log_types"    : ["log", "info", "warn", "error"]
    },
    "py": {
        "consoleStr"   : "{title}, {variable}",
        "consoleFunc"  : ["print"],
        "single_quotes": false
    },
    "php": {
        "consoleFunc"  : ["print_r"],   // var_dump or if you have custom logger ["$logger", "debug"] output: $logger->debug($variable);
        "preTag"       : true,          // Put log in pre tag like echo '<pre>'; print_r($variable); echo '</pre>';
        "dieAfterLog"  : false          // echo '<pre>'; print_r($variable); echo '</pre>'; die();
    },
    "fileTypeMap" : {                   // Maps file type to wrapper. For example "text.html.vue": "js" means use js wrapper in vue js files
        "text.html.vue"  : "js",        // php,python,js is included by dafault ("embedding.php": "php", "source.js": "js", "source.python": "py")
        "source.ts"      : "js",
        "source.tsx"     : "js",
        "source.coffee"  : "js",
        "text.html.basic": "js",
        "text.html.blade": "js",
        "text.html.twig" : "js"
    }
}
```
