### ISSUE TITLE
NameError: global name 'is_log_statement' is not defined

### ISSUE THREAD

**Issue by unlight** [unknownuser88/consolewrap#8]
ST3 Console

```
Traceback (most recent call last):
  File "D:\Progs\Sublime_Text\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "consolewrap in D:\Progs\Sublime_Text\Data\Installed Packages\Console Wrap for js.sublime-package", line 76, in run
NameError: global name 'is_log_statement' is not defined
```

**Comment by unknownuser88** [comment]
fixed in version 0.1.0
